[package]
name = "rust_folder_organizer"
version = "0.1.0"
authors = ["Mitchell Ponchione <mitchell.ponchione@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
